apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}-http
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    service: http
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
