apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}-transport
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
    service: transport
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.transport.type }}
  ports:
    - name: transport
      port: {{ .Values.service.transport.port }}
      targetPort: transport
      protocol: TCP
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
